---
:orientdb:
 :server: 10.222.148.109 
 #:server: localhost  
 :port: 2480
 :logger: stdout           # 'file' or 'stdout'
 :database: 
   :development: devel 
   :production: produc
   :test:  temp
 :admin:
   :user: ***w
   :pass: ***c
 :auth:
   :user: root
   :pass: ****s

# hfx: 101
