---
:orientdb:
 :server: 10.222.148.109 # 172.28.50.25 
  #:server:  172.28.50.25 
  #:server: localhost  # 172.28.50.109 #  #mailout.halfgarten-capital.de
 :port: 2480
 :logger: stdout           # 'file' or 'stdout'
 :database: 
   :development: ml_data
   :production: hcn_data
   :test:  temp
 :admin:
   :user: ***w
   :pass: ***c
 :auth:
   :user: root
   :pass: ****s

# hfx: 101
